# Translations template for keystone.
# Copyright (C) 2015 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: keystone 2015.1.dev183\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2015-02-03 06:04+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: keystone/clean.py:24
#, python-format
msgid "%s cannot be empty."
msgstr ""

#: keystone/clean.py:26
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr ""

#: keystone/clean.py:31
#, python-format
msgid "%(property_name)s should not be greater than %(max_length)s characters."
msgstr ""

#: keystone/clean.py:40
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr ""

#: keystone/cli.py:222
msgid "At least one option must be provided"
msgstr ""

#: keystone/cli.py:229
msgid "--all option cannot be mixed with other options"
msgstr ""

#: keystone/cli.py:238
#, python-format
msgid "Unknown domain '%(name)s' specified by --domain-name"
msgstr ""

#: keystone/exception.py:79
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s - the server could not "
"comply with the request since it is either malformed or otherwise "
"incorrect. The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:90
#, python-format
msgid "%(detail)s"
msgstr ""

#: keystone/exception.py:94
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""

#: keystone/exception.py:103
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the "
"limit of column %(type)s(CHAR(%(length)d))."
msgstr ""

#: keystone/exception.py:109
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. "
"The server could not comply with the request because the attribute size "
"is invalid (too large). The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:119
#, python-format
msgid ""
"The password length must be less than or equal to %(size)i. The server "
"could not comply with the request because the password is invalid."
msgstr ""

#: keystone/exception.py:127
#, python-format
msgid ""
"Unable to delete region %(region_id)s because it or its child regions "
"have associated endpoints."
msgstr ""

#: keystone/exception.py:134
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr ""

#: keystone/exception.py:143
msgid "(Disable debug mode to suppress these details.)"
msgstr ""

#: keystone/exception.py:148
#, python-format
msgid "%(message)s %(amendment)s"
msgstr ""

#: keystone/exception.py:156
msgid "The request you have made requires authentication."
msgstr ""

#: keystone/exception.py:162
msgid "Authentication plugin error."
msgstr ""

#: keystone/exception.py:170
#, python-format
msgid "Unable to find valid groups while using mapping %(mapping_id)s"
msgstr ""

#: keystone/exception.py:175
msgid "Attempted to authenticate with an unsupported method."
msgstr ""

#: keystone/exception.py:183
msgid "Additional authentications steps required."
msgstr ""

#: keystone/exception.py:191
msgid "You are not authorized to perform the requested action."
msgstr ""

#: keystone/exception.py:198
#, python-format
msgid "You are not authorized to perform the requested action: %(action)s"
msgstr ""

#: keystone/exception.py:203
#, python-format
msgid ""
"Could not change immutable attribute(s) '%(attributes)s' in target "
"%(target)s"
msgstr ""

#: keystone/exception.py:208
#, python-format
msgid ""
"Group membership across backend boundaries is not allowed, group in "
"question is %(group_id)s, user is %(user_id)s"
msgstr ""

#: keystone/exception.py:214
#, python-format
msgid ""
"Invalid mix of entities for policy association - only Endpoint, Service "
"or Region+Service allowed. Request was - Endpoint: %(endpoint_id)s, "
"Service: %(service_id)s, Region: %(region_id)s"
msgstr ""

#: keystone/exception.py:221
#, python-format
msgid "Could not find: %(target)s"
msgstr ""

#: keystone/exception.py:227
#, python-format
msgid "Could not find endpoint: %(endpoint_id)s"
msgstr ""

#: keystone/exception.py:234
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr ""

#: keystone/exception.py:239
#, python-format
msgid "Could not find policy: %(policy_id)s"
msgstr ""

#: keystone/exception.py:243
msgid "Could not find policy association"
msgstr ""

#: keystone/exception.py:247
#, python-format
msgid "Could not find role: %(role_id)s"
msgstr ""

#: keystone/exception.py:251
#, python-format
msgid "Could not find region: %(region_id)s"
msgstr ""

#: keystone/exception.py:255
#, python-format
msgid "Could not find service: %(service_id)s"
msgstr ""

#: keystone/exception.py:259
#, python-format
msgid "Could not find domain: %(domain_id)s"
msgstr ""

#: keystone/exception.py:263
#, python-format
msgid "Could not find project: %(project_id)s"
msgstr ""

#: keystone/exception.py:267
#, python-format
msgid "Cannot create project with parent: %(project_id)s"
msgstr ""

#: keystone/exception.py:271
#, python-format
msgid "Could not find token: %(token_id)s"
msgstr ""

#: keystone/exception.py:275
#, python-format
msgid "Could not find user: %(user_id)s"
msgstr ""

#: keystone/exception.py:279
#, python-format
msgid "Could not find group: %(group_id)s"
msgstr ""

#: keystone/exception.py:283
#, python-format
msgid "Could not find mapping: %(mapping_id)s"
msgstr ""

#: keystone/exception.py:287
#, python-format
msgid "Could not find trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:291
#, python-format
msgid "No remaining uses for trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:295
#, python-format
msgid "Could not find credential: %(credential_id)s"
msgstr ""

#: keystone/exception.py:299
#, python-format
msgid "Could not find version: %(version)s"
msgstr ""

#: keystone/exception.py:303
#, python-format
msgid "Could not find Endpoint Group: %(endpoint_group_id)s"
msgstr ""

#: keystone/exception.py:307
#, python-format
msgid "Could not find Identity Provider: %(idp_id)s"
msgstr ""

#: keystone/exception.py:311
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for Identity Provider: "
"%(idp_id)s"
msgstr ""

#: keystone/exception.py:322
#, python-format
msgid "Conflict occurred attempting to store %(type)s - %(details)s"
msgstr ""

#: keystone/exception.py:330
msgid "An unexpected error prevented the server from fulfilling your request."
msgstr ""

#: keystone/exception.py:333
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request: "
"%(exception)s"
msgstr ""

#: keystone/exception.py:356
#, python-format
msgid "Unable to parse policy file %(policy_file)s."
msgstr ""

#: keystone/exception.py:360
#, python-format
msgid "Unable to consume trust %(trust_id)s, unable to acquire lock."
msgstr ""

#: keystone/exception.py:365
msgid ""
"Expected signing certificates are not available on the server. Please "
"check Keystone configuration."
msgstr ""

#: keystone/exception.py:371
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr ""

#: keystone/exception.py:376
#, python-format
msgid ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in "
"the backend."
msgstr ""

#: keystone/exception.py:381
#, python-format
msgid "Error while reading metadata file, %(reason)s"
msgstr ""

#: keystone/exception.py:385
#, python-format
msgid ""
"Unexpected combination of grant attributes - User: %(user_id)s, Group: "
"%(group_id)s, Project: %(project_id)s, Domain: %(domain_id)s"
msgstr ""

#: keystone/exception.py:392
msgid "The action you have requested has not been implemented."
msgstr ""

#: keystone/exception.py:399
msgid "The service you have requested is no longer available on this server."
msgstr ""

#: keystone/exception.py:406
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr ""

#: keystone/exception.py:411
#, python-format
msgid ""
"The Keystone domain configuration file %(config_file)s defines an "
"additional SQL driver - only one is permitted."
msgstr ""

#: keystone/exception.py:418
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration "
"repository path at %(path)s doesn't exist or isn't a directory."
msgstr ""

#: keystone/exception.py:430
#, python-format
msgid ""
"Unable to sign SAML assertion. It is likely that this server does not "
"have xmlsec1 installed, or this is the result of misconfiguration. Reason"
" %(reason)s"
msgstr ""

#: keystone/notifications.py:148
#, python-format
msgid "%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr ""

#: keystone/notifications.py:157
#, python-format
msgid "Method not callable: %s"
msgstr ""

#: keystone/assignment/controllers.py:110
#: keystone/assignment/controllers.py:224 keystone/identity/controllers.py:67
msgid "Name field is required and cannot be empty"
msgstr ""

#: keystone/assignment/controllers.py:165
msgid "Marker could not be found"
msgstr ""

#: keystone/assignment/controllers.py:176
msgid "Invalid limit value"
msgstr ""

#: keystone/assignment/controllers.py:431
msgid ""
"Cannot use parents_as_list and parents_as_ids query params at the same "
"time."
msgstr ""

#: keystone/assignment/controllers.py:514
msgid "Specify a domain or project, not both"
msgstr ""

#: keystone/assignment/controllers.py:519
msgid "Specify a user or group, not both"
msgstr ""

#: keystone/assignment/core.py:232
msgid "Must specify either domain or project"
msgstr ""

#: keystone/assignment/core.py:496
#, python-format
msgid "Project (%s)"
msgstr ""

#: keystone/assignment/core.py:498
#, python-format
msgid "Domain (%s)"
msgstr ""

#: keystone/assignment/core.py:500
msgid "Unknown Target"
msgstr ""

#: keystone/assignment/backends/ldap.py:87
msgid "Domain metadata not supported by LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:368
#, python-format
msgid "User %(user_id)s already has role %(role_id)s in tenant %(tenant_id)s"
msgstr ""

#: keystone/assignment/backends/ldap.py:374
#, python-format
msgid "Role %s not found"
msgstr ""

#: keystone/assignment/backends/ldap.py:389
#: keystone/assignment/backends/sql.py:327
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr ""

#: keystone/assignment/backends/sql.py:348
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr ""

#: keystone/assignment/role_backends/ldap.py:60 keystone/catalog/core.py:106
#: keystone/common/ldap/core.py:1406 keystone/resource/backends/ldap.py:148
#, python-format
msgid "Duplicate ID, %s."
msgstr ""

#: keystone/assignment/role_backends/ldap.py:68
#: keystone/common/ldap/core.py:1396
#, python-format
msgid "Duplicate name, %s."
msgstr ""

#: keystone/assignment/role_backends/ldap.py:118
#, python-format
msgid "Cannot duplicate name %s"
msgstr ""

#: keystone/auth/controllers.py:59
#, python-format
msgid ""
"Cannot load an auth-plugin by class-name without a \"method\" attribute "
"defined: %s"
msgstr ""

#: keystone/auth/controllers.py:70
#, python-format
msgid ""
"Auth plugin %(plugin)s is requesting previously registered method "
"%(method)s"
msgstr ""

#: keystone/auth/controllers.py:114
#, python-format
msgid ""
"Unable to reconcile identity attribute %(attribute)s as it has "
"conflicting values %(new)s and %(old)s"
msgstr ""

#: keystone/auth/controllers.py:331
msgid "Scoping to both domain and project is not allowed"
msgstr ""

#: keystone/auth/controllers.py:334
msgid "Scoping to both domain and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:337
msgid "Scoping to both project and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:503
msgid "User not found"
msgstr ""

#: keystone/auth/controllers.py:607
msgid "A project-scoped token is required to produce a service catalog."
msgstr ""

#: keystone/auth/plugins/external.py:46
msgid "No authenticated user"
msgstr ""

#: keystone/auth/plugins/external.py:56
#, python-format
msgid "Unable to lookup user %s"
msgstr ""

#: keystone/auth/plugins/external.py:107
msgid "auth_type is not Negotiate"
msgstr ""

#: keystone/auth/plugins/mapped.py:210
msgid "Could not map user"
msgstr ""

#: keystone/auth/plugins/oauth1.py:39
#, python-format
msgid "%s not supported"
msgstr ""

#: keystone/auth/plugins/oauth1.py:57
msgid "Access token is expired"
msgstr ""

#: keystone/auth/plugins/oauth1.py:71
msgid "Could not validate the access token"
msgstr ""

#: keystone/auth/plugins/password.py:134
msgid "Invalid username or password"
msgstr ""

#: keystone/catalog/controllers.py:165
#, python-format
msgid "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""
msgstr ""

#: keystone/common/authorization.py:46 keystone/common/wsgi.py:61
#, python-format
msgid "token reference must be a KeystoneToken type, got: %s"
msgstr ""

#: keystone/common/base64utils.py:66
msgid "pad must be single character"
msgstr ""

#: keystone/common/base64utils.py:215
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before 2nd to last char"
msgstr ""

#: keystone/common/base64utils.py:219
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before non-pad last char"
msgstr ""

#: keystone/common/base64utils.py:225
#, python-format
msgid "text is not a multiple of 4, but contains pad \"%s\""
msgstr ""

#: keystone/common/base64utils.py:244 keystone/common/base64utils.py:265
msgid "padded base64url text must be multiple of 4 characters"
msgstr ""

#: keystone/common/controller.py:288 keystone/identity/core.py:326
#: keystone/resource/core.py:709 keystone/resource/backends/ldap.py:60
#, python-format
msgid "Expected dict or list: %s"
msgstr ""

#: keystone/common/controller.py:585
msgid "Cannot change Domain ID"
msgstr ""

#: keystone/common/controller.py:614
msgid "domain_id is required as part of entity"
msgstr ""

#: keystone/common/controller.py:649
msgid "A domain-scoped token must be used"
msgstr ""

#: keystone/common/dependency.py:48
#, python-format
msgid "Unregistered dependency: %(name)s for %(targets)s"
msgstr ""

#: keystone/common/dependency.py:88
msgid "event_callbacks must be a dict"
msgstr ""

#: keystone/common/dependency.py:93
#, python-format
msgid "event_callbacks[%s] must be a dict"
msgstr ""

#: keystone/common/pemutils.py:223
#, python-format
msgid "unknown pem_type \"%(pem_type)s\", valid types are: %(valid_pem_types)s"
msgstr ""

#: keystone/common/pemutils.py:242
#, python-format
msgid ""
"unknown pem header \"%(pem_header)s\", valid headers are: "
"%(valid_pem_headers)s"
msgstr ""

#: keystone/common/pemutils.py:298
#, python-format
msgid "failed to find end matching \"%s\""
msgstr ""

#: keystone/common/pemutils.py:302
#, python-format
msgid ""
"beginning & end PEM headers do not match (%(begin_pem_header)s!= "
"%(end_pem_header)s)"
msgstr ""

#: keystone/common/pemutils.py:377
#, python-format
msgid "unknown pem_type: \"%s\""
msgstr ""

#: keystone/common/pemutils.py:389
#, python-format
msgid ""
"failed to base64 decode %(pem_type)s PEM at position%(position)d: "
"%(err_msg)s"
msgstr ""

#: keystone/common/utils.py:164 keystone/credential/controllers.py:44
msgid "Invalid blob in credential"
msgstr ""

#: keystone/common/wsgi.py:315
#, python-format
msgid "%s field is required and cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:327
#, python-format
msgid "%s field(s) cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:544
msgid "The resource could not be found."
msgstr ""

#: keystone/common/cache/_memcache_pool.py:111
#, python-format
msgid "Unable to get a connection from pool id %(id)s after %(seconds)s seconds."
msgstr ""

#: keystone/common/cache/core.py:132
msgid "region not type dogpile.cache.CacheRegion"
msgstr ""

#: keystone/common/cache/backends/mongo.py:231
msgid "db_hosts value is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:236
msgid "database db_name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:241
msgid "cache_collection name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:252
msgid "integer value expected for w (write concern attribute)"
msgstr ""

#: keystone/common/cache/backends/mongo.py:260
msgid "replicaset_name required when use_replica is True"
msgstr ""

#: keystone/common/cache/backends/mongo.py:275
msgid "integer value expected for mongo_ttl_seconds"
msgstr ""

#: keystone/common/cache/backends/mongo.py:301
msgid "no ssl support available"
msgstr ""

#: keystone/common/cache/backends/mongo.py:310
#, python-format
msgid ""
"Invalid ssl_cert_reqs value of %s, must be one of \"NONE\", \"OPTIONAL\","
" \"REQUIRED\""
msgstr ""

#: keystone/common/kvs/core.py:71
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:106
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr ""

#: keystone/common/kvs/core.py:145
#, python-format
msgid "Key Value Store not configured: %s"
msgstr ""

#: keystone/common/kvs/core.py:198
msgid "`key_mangler` option must be a function reference"
msgstr ""

#: keystone/common/kvs/core.py:352
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:356
msgid "Must be called within an active lock context."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:69
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:108
#, python-format
msgid ""
"Backend `%(driver)s` is not a valid memcached backend. Valid drivers: "
"%(driver_list)s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:179
msgid "`key_mangler` functions must be callable."
msgstr ""

#: keystone/common/ldap/core.py:196
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:206
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:218
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:593
msgid "Invalid TLS / LDAPS combination"
msgstr ""

#: keystone/common/ldap/core.py:598
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr ""

#: keystone/common/ldap/core.py:608
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr ""

#: keystone/common/ldap/core.py:620
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr ""

#: keystone/common/ldap/core.py:1331
#, python-format
msgid "ID attribute %(id_attr)s not found in LDAP object %(dn)s"
msgstr ""

#: keystone/common/ldap/core.py:1375
#, python-format
msgid "LDAP %s create"
msgstr ""

#: keystone/common/ldap/core.py:1380
#, python-format
msgid "LDAP %s update"
msgstr ""

#: keystone/common/ldap/core.py:1385
#, python-format
msgid "LDAP %s delete"
msgstr ""

#: keystone/common/ldap/core.py:1527
msgid ""
"Disabling an entity where the 'enable' attribute is ignored by "
"configuration."
msgstr ""

#: keystone/common/ldap/core.py:1538
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr ""

#: keystone/common/ldap/core.py:1625
#, python-format
msgid "Member %(member)s is already a member of group %(group)s"
msgstr ""

#: keystone/common/sql/core.py:219
msgid ""
"Cannot truncate a driver call without hints list as first parameter after"
" self "
msgstr ""

#: keystone/common/sql/core.py:401
msgid "Duplicate Entry"
msgstr ""

#: keystone/common/sql/core.py:417
#, python-format
msgid "An unexpected error occurred when trying to store %s"
msgstr ""

#: keystone/common/sql/migration_helpers.py:184
#: keystone/common/sql/migration_helpers.py:223
#, python-format
msgid "%s extension does not exist."
msgstr ""

#: keystone/common/validation/validators.py:54
#, python-format
msgid "Invalid input for field '%(path)s'. The value is '%(value)s'."
msgstr ""

#: keystone/contrib/ec2/controllers.py:318
msgid "Token belongs to another user"
msgstr ""

#: keystone/contrib/ec2/controllers.py:346
msgid "Credential belongs to another user"
msgstr ""

#: keystone/contrib/endpoint_filter/backends/sql.py:69
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr ""

#: keystone/contrib/endpoint_filter/backends/sql.py:180
msgid "Endpoint Group Project Association not found"
msgstr ""

#: keystone/contrib/endpoint_policy/core.py:258
#, python-format
msgid "No policy is associated with endpoint %(endpoint_id)s."
msgstr ""

#: keystone/contrib/federation/controllers.py:280
msgid "Use a project scoped token when attempting to create a SAML assertion"
msgstr ""

#: keystone/contrib/federation/idp.py:454
#, python-format
msgid "Cannot open certificate %(cert_file)s. Reason: %(reason)s"
msgstr ""

#: keystone/contrib/federation/idp.py:521
msgid "Ensure configuration option idp_entity_id is set."
msgstr ""

#: keystone/contrib/federation/idp.py:524
msgid "Ensure configuration option idp_sso_endpoint is set."
msgstr ""

#: keystone/contrib/federation/idp.py:544
msgid ""
"idp_contact_type must be one of: [technical, other, support, "
"administrative or billing."
msgstr ""

#: keystone/contrib/federation/utils.py:122
msgid "Federation token is expired"
msgstr ""

#: keystone/contrib/federation/utils.py:152
msgid ""
"Could not find Identity Provider identifier in environment, check "
"[federation] remote_id_attribute for details."
msgstr ""

#: keystone/contrib/federation/utils.py:157
msgid ""
"Incoming identity provider identifier not included among the accepeted "
"identifiers."
msgstr ""

#: keystone/contrib/federation/utils.py:608
#, python-format
msgid "Identity Provider %(idp)s is disabled"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:96
msgid "Cannot change consumer secret"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:128
msgid "Cannot list request tokens with a token issued via delegation."
msgstr ""

#: keystone/contrib/oauth1/controllers.py:188
#: keystone/contrib/oauth1/backends/sql.py:267
msgid "User IDs do not match"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:195
msgid "Could not find role"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:238
msgid "Invalid signature"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:287
#: keystone/contrib/oauth1/controllers.py:363
msgid "Request token is expired"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:301
msgid "There should not be any non-oauth parameters"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:305
msgid "provided consumer key does not match stored consumer key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:309
msgid "provided verifier does not match stored verifier"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:313
msgid "provided request key does not match stored request key"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:317
msgid "Request Token does not have an authorizing user id"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:352
msgid "Cannot authorize a request token with a token issued via delegation."
msgstr ""

#: keystone/contrib/oauth1/controllers.py:382
msgid "authorizing user does not have role required"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:395
msgid "User is not a member of the requested project"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:88
msgid "Consumer not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:183
msgid "Request token not found"
msgstr ""

#: keystone/contrib/oauth1/backends/sql.py:247
msgid "Access token not found"
msgstr ""

#: keystone/contrib/revoke/controllers.py:33
#, python-format
msgid "invalid date format %s"
msgstr ""

#: keystone/contrib/revoke/core.py:152
msgid ""
"The revoke call must not have both domain_id and project_id. This is a "
"bug in the Keystone server. The current request is aborted."
msgstr ""

#: keystone/contrib/revoke/core.py:221 keystone/token/provider.py:235
#: keystone/token/provider.py:257 keystone/token/provider.py:352
#: keystone/token/provider.py:359
msgid "Failed to validate token"
msgstr ""

#: keystone/identity/controllers.py:70
msgid "Enabled field must be a boolean"
msgstr ""

#: keystone/identity/controllers.py:96
msgid "Enabled field should be a boolean"
msgstr ""

#: keystone/identity/core.py:215 keystone/identity/backends/ldap.py:59
#: keystone/identity/backends/ldap.py:61 keystone/identity/backends/ldap.py:67
#: keystone/identity/backends/ldap.py:69 keystone/identity/backends/sql.py:109
#: keystone/identity/backends/sql.py:111
msgid "Invalid user / password"
msgstr ""

#: keystone/identity/core.py:590 keystone/token/core.py:58
#, python-format
msgid "User is disabled: %s"
msgstr ""

#: keystone/identity/core.py:632
msgid "Cannot change user ID"
msgstr ""

#: keystone/identity/backends/ldap.py:99
msgid "Cannot change user name"
msgstr ""

#: keystone/identity/backends/ldap.py:188 keystone/identity/backends/sql.py:193
#: keystone/identity/backends/sql.py:211
#, python-format
msgid "User '%(user_id)s' not found in group '%(group_id)s'"
msgstr ""

#: keystone/identity/backends/ldap.py:338
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr ""

#: keystone/models/token_model.py:61
msgid "Found invalid token: scoped to both project and domain."
msgstr ""

#: keystone/openstack/common/log.py:298
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: keystone/openstack/common/log.py:406
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: keystone/openstack/common/log.py:467
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: keystone/openstack/common/log.py:715
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: keystone/openstack/common/policy.py:111
msgid "The JSON file that defines policies."
msgstr ""

#: keystone/openstack/common/policy.py:114
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: keystone/openstack/common/policy.py:118
msgid ""
"Directories where policy configuration files are stored. They can be "
"relative to any directory in the search path defined by the config_dir "
"option, or absolute paths. The file defined by policy_file must exist for"
" these directories to be searched."
msgstr ""

#: keystone/openstack/common/policy.py:142
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: keystone/openstack/common/policy.py:239
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: keystone/openstack/common/versionutils.py:90
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: keystone/openstack/common/versionutils.py:94
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: keystone/openstack/common/versionutils.py:98
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s."
msgstr ""

#: keystone/openstack/common/versionutils.py:101
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s. It will not be superseded."
msgstr ""

#: keystone/resource/core.py:80
#, python-format
msgid "max hierarchy depth reached for %s branch."
msgstr ""

#: keystone/resource/core.py:98
msgid "cannot create a project within a different domain than its parents."
msgstr ""

#: keystone/resource/core.py:102
#, python-format
msgid "cannot create a project in a branch containing a disabled project: %s"
msgstr ""

#: keystone/resource/core.py:123 keystone/token/core.py:66
#: keystone/token/core.py:82
#, python-format
msgid "Domain is disabled: %s"
msgstr ""

#: keystone/resource/core.py:134
#, python-format
msgid "Project is disabled: %s"
msgstr ""

#: keystone/resource/core.py:154
#, python-format
msgid "cannot enable project %s since it has disabled parents"
msgstr ""

#: keystone/resource/core.py:162
#, python-format
msgid "cannot disable project %s since its subtree contains enabled projects"
msgstr ""

#: keystone/resource/core.py:174
msgid "Update of `parent_id` is not allowed."
msgstr ""

#: keystone/resource/core.py:201
#, python-format
msgid "cannot delete the project %s since it is not a leaf in the hierarchy."
msgstr ""

#: keystone/resource/core.py:298
msgid "Multiple domains are not supported"
msgstr ""

#: keystone/resource/core.py:345
msgid "delete the default domain"
msgstr ""

#: keystone/resource/core.py:356
msgid "cannot delete a domain that is enabled, please disable it first."
msgstr ""

#: keystone/resource/backends/ldap.py:150
#: keystone/resource/backends/ldap.py:158
#: keystone/resource/backends/ldap.py:162
msgid "Domains are read-only against LDAP"
msgstr ""

#: keystone/token/controllers.py:385
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr ""

#: keystone/token/controllers.py:404 keystone/token/controllers.py:407
msgid "Token does not belong to specified tenant."
msgstr ""

#: keystone/token/core.py:73
#, python-format
msgid "Tenant is disabled: %s"
msgstr ""

#: keystone/token/provider.py:143
msgid ""
"Unrecognized keystone.conf [signing] token_format: expected either 'UUID'"
" or 'PKI'"
msgstr ""

#: keystone/token/persistence/backends/kvs.py:133
#, python-format
msgid "Unknown token version %s"
msgstr ""

#: keystone/token/providers/common.py:195
#: keystone/token/providers/common.py:300
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr ""

#: keystone/token/providers/common.py:200
#: keystone/token/providers/common.py:305
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr ""

#: keystone/token/providers/common.py:227
msgid "Trustor is disabled."
msgstr ""

#: keystone/token/providers/common.py:291
msgid "Trustee has no delegated roles."
msgstr ""

#: keystone/token/providers/common.py:344
#, python-format
msgid "Invalid audit info data type: %(data)s (%(type)s)"
msgstr ""

#: keystone/token/providers/common.py:365
msgid "User is not a trustee."
msgstr ""

#: keystone/token/providers/common.py:446
msgid "Oauth is disabled."
msgstr ""

#: keystone/token/providers/common.py:503
msgid "Non-default domain is not supported"
msgstr ""

#: keystone/token/providers/common.py:511
msgid "Domain scoped token is not supported"
msgstr ""

#: keystone/token/providers/pki.py:48 keystone/token/providers/pkiz.py:30
msgid "Unable to sign token."
msgstr ""

#: keystone/trust/controllers.py:146
msgid "Redelegation allowed for delegated by trust only"
msgstr ""

#: keystone/trust/controllers.py:174
msgid "The authenticated user should match the trustor."
msgstr ""

#: keystone/trust/controllers.py:179
msgid "At least one role should be specified."
msgstr ""

#: keystone/trust/core.py:57
#, python-format
msgid ""
"Remaining redelegation depth of %(redelegation_depth)d out of allowed "
"range of [0..%(max_count)d]"
msgstr ""

#: keystone/trust/core.py:66
#, python-format
msgid ""
"Field \"remaining_uses\" is set to %(value)s while it must not be set in "
"order to redelegate a trust"
msgstr ""

#: keystone/trust/core.py:77
msgid "Requested expiration time is more than redelegated trust can provide"
msgstr ""

#: keystone/trust/core.py:87
msgid "Some of requested roles are not in redelegated trust"
msgstr ""

#: keystone/trust/core.py:116
msgid "One of the trust agents is disabled or deleted"
msgstr ""

#: keystone/trust/core.py:135
msgid "remaining_uses must be a positive integer or null."
msgstr ""

#: keystone/trust/core.py:141
#, python-format
msgid ""
"Requested redelegation depth of %(requested_count)d is greater than "
"allowed %(max_count)d"
msgstr ""

#: keystone/trust/core.py:147
msgid "remaining_uses must not be set if redelegation is allowed"
msgstr ""

#: keystone/trust/core.py:157
msgid ""
"Modifying \"redelegation_count\" upon redelegation is forbidden. Omitting"
" this parameter is advised."
msgstr ""

