Description: CVE-2013-2059 Revoke tokens on user delete
 Sam Stoelinga reported a vulnerability in Keystone. When users are deleted
 through Keystone v2 API, existing tokens for those users are not immediately
 invalidated and remain valid for the duration of the token's life (by default,
 up to 24 hours). This may result in users retaining access when the
 administrator of the system thought them disabled. You can workaround this
 issue by disabling a user before deleting it: in that case the tokens
 belonging to the disabled user are immediately invalidated. Keystone setups
 using the v3 API call to delete users are unaffected.
Author: Dolph Mathews <dolph.mathews@gmail.com>
Origin: Upstream, https://review.openstack.org/#/c/28678/
Ubuntu-Bug: https://bugs.launchpad.net/bugs/1166670
Debian-Bug: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=707598
Date: 2013-05-10

Index: keystone/keystone/identity/core.py
===================================================================
--- keystone.orig/keystone/identity/core.py	2013-05-10 10:13:14.000000000 +0800
+++ keystone/keystone/identity/core.py	2013-05-10 10:13:34.000000000 +0800
@@ -427,6 +427,14 @@
             raise exception.UserNotFound(user_id=user_id)
 
         self.identity_api.delete_user(context, user_id)
+        try:
+            for token_id in self.token_api.list_tokens(context, user_id):
+                self.token_api.delete_token(context, token_id)
+        except exception.NotImplemented:
+            # The users status has been changed but tokens remain valid for
+            # backends that can't list tokens for users
+            LOG.warning('User %s status has changed, but existing tokens '
+                        'remain valid' % user_id)
 
     def set_user_enabled(self, context, user_id, user):
         return self.update_user(context, user_id, user)
Index: keystone/tests/test_keystoneclient.py
===================================================================
--- keystone.orig/tests/test_keystoneclient.py	2013-05-10 10:13:14.000000000 +0800
+++ keystone/tests/test_keystoneclient.py	2013-05-10 10:13:34.000000000 +0800
@@ -327,6 +327,30 @@
                           self.get_client,
                           self.user_foo)
 
+    def test_delete_user_invalidates_token(self):
+        from keystoneclient import exceptions as client_exceptions
+
+        admin_client = self.get_client(admin=True)
+        client = self.get_client(admin=False)
+
+        username = uuid.uuid4().hex
+        password = uuid.uuid4().hex
+        user_id = admin_client.users.create(
+            name=username, password=password, email=uuid.uuid4().hex).id
+
+        token_id = client.tokens.authenticate(
+            username=username, password=password).id
+
+        # token should be usable before the user is deleted
+        client.tokens.authenticate(token=token_id)
+
+        admin_client.users.delete(user=user_id)
+
+        # authenticate with a token should not work after the user is deleted
+        self.assertRaises(client_exceptions.Unauthorized,
+                          client.tokens.authenticate,
+                          token=token_id)
+
     def test_token_expiry_maintained(self):
         foo_client = self.get_client(self.user_foo)
         orig_token = foo_client.service_catalog.catalog['token']
